services:
    vllm_qwen3_32B:
        platform: linux/amd64
        image: vllm/vllm-openai:v0.17.1
        container_name: vllm_qwen3_32B
        ports:
            - ${LLM_API_PORT}:8000
        environment:
            - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
        runtime: nvidia
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          device_ids: ["0"]
                          capabilities: [gpu]
        ipc: host
        volumes:
            - ${HUGGING_FACE_CACHE_DIR}:/root/.cache/huggingface
        command: >
            --port 8000
            --model Qwen/Qwen3-32B-AWQ
            --max-model-len 6000
            --gpu-memory-utilization 0.90
            --enable-auto-tool-choice
            --tool-call-parser hermes
            --tensor-parallel-size 1
            --max-num-seqs 1
            --reasoning-parser deepseek_r1

    docling-serve:
        image: quay.io/docling-project/docling-serve-cu124:latest
        container_name: docling-serve-text-mate
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          device_ids: ["1"]
                          capabilities: [gpu]
        ports:
            - ${DOCLING_API_PORT}:5001
        environment:
            - DOCLING_MODELS_PATH=/models
            - DOCLING_CONFIG_FILE=/app/docling_config.json
            - DOCLING_SERVE_ENABLE_UI=true
        volumes:
            - "${HOME}/.cache/docling:/models"
